---
- name: Creat VM on OCP Virt
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Create a VirtualMachine
      redhat.openshift_virtualization.kubevirt_vm:
        state: present
        name: windows-2019
        namespace: openshift-virualization-os-images
        labels:
          app: 
        instancetype:
          name: u1.medium
        preference:
          name: windoows-2019
        spec:
          source:
            http:
              url: 'https://www.opentlc.com/download/ocp4_virt_foundations/Windows2019.iso'
          storage:
            resources:
              requests:
                storage: 5Gi
      wait: true
    - name: Create my first VM
      kubevirt_vm:
        namespace: default
        name: vm1
        cpu_cores: 1
        memory: 64Mi
        disks:
          - name: containerdisk
            volume:
              containerDisk:
                image: kubevirt/cirros-container-disk-demo:latest
            disk:
              bus: virtio   